### ISSUE TITLE
Unknown Problem Building JavaScript

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2JavaScript#36]
There is a consistent problem when building code for the JavaScript platform.  For example, when building `std.wy` we get this:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at wybs.util.AbstractSyntacticHeap.getSyntacticItem(AbstractSyntacticHeap.java:72)
        at wybs.util.AbstractSyntacticHeap.getRootItem(AbstractSyntacticHeap.java:62)
        at wybs.util.AbstractSyntacticHeap.findAll(AbstractSyntacticHeap.java:175)
        at wycc.commands.Build.extractSyntacticMarkers(Build.java:192)
        at wycc.commands.Build.printSyntacticMarkers(Build.java:143)
        at wycc.commands.Build.execute(Build.java:128)
        at wycc.WyProject.execute(WyProject.java:244)
        at wycc.WyMain.execute(WyMain.java:327)
        at wycc.WyMain.main(WyMain.java:422)
```
The weird thing is that the JavaScript is actually generated.

**Comment by DavePearce** [comment]
**UPDATE:** The problem was that `JavaScriptFile` extended `AbstractCompilationUnit` which meant is was being viewed as a `SyntacticHeap` when extracting markers.  However, it wasn't really implemented as a `SyntacticHeap`.  For now, have changed it not to extend anything which solves the problem.  In the future, may want to revisit and make it properly implement `SyntacticHeap`.
