### ISSUE TITLE
Problem Refreshing JavaScriptFile

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2JavaScript#39]
There is currently a problem that arises whenever we try to rebuild a JavaScript project.  The following illustrates the trace:

```
djp@Workstation:~/projects/TMP.wy$ wy build
Exception in thread "main" java.lang.UnsupportedOperationException
	at wyjs.core.JavaScriptFile$1.read(JavaScriptFile.java:48)
	at wyjs.core.JavaScriptFile$1.read(JavaScriptFile.java:1)
	at wyfs.util.AbstractEntry.read(AbstractEntry.java:79)
	...
```

Basically, the file system is attempting to sync with the javaScriptFile stored on disk but, currently, there is no parser.  It's not clear to me what the right solution is here.

**Comment by DavePearce** [comment]
This issue has been fixed by getting the `JavaScriptFile.ContentType` to return an empty `JavaScriptFile` upon a `read` action.  That is not really an ideal solution long term.  However, it essentially works for now, until such time that a proper solution can be determined.
