### ISSUE TITLE
NullPointerException Type.Reference.getElement()

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2JavaScript#62]
Building `Web.wy` currently generates the following error:

```
[INFO] Java output "Exception in thread "main" java.lang.NullPointerException: Cannot invoke "wyil.lang.WyilFile$Type$Reference.getElement()" because "type" is null
	at wyjs.tasks.JavaScriptCompiler.isBoxedType(JavaScriptCompiler.java:2148)
	at wyjs.tasks.JavaScriptCompiler.constructNew(JavaScriptCompiler.java:766)
	at wyjs.tasks.JavaScriptCompiler.constructNew(JavaScriptCompiler.java:78)
	at wyil.util.AbstractTranslator.visitNew(AbstractTranslator.java:870)
	at wyil.util.AbstractTranslator.visitUnaryOperator(AbstractTranslator.java:539)
	at wyil.util.AbstractTranslator.visitExpression(AbstractTranslator.java:474)
	at wyil.util.AbstractTranslator.visitInitialiser(AbstractTranslator.java:331)
	at wyil.util.AbstractTranslator.visitStatement(AbstractTranslator.java:179)
	at wyil.util.AbstractTranslator.visitBlock(AbstractTranslator.java:277)
	at wyil.util.AbstractTranslator.visitMethod(AbstractTranslator.java:148)
	at wyil.util.AbstractTranslator.visitFunctionOrMethod(AbstractTranslator.java:121)
	at wyil.util.AbstractTranslator.visitCallable(AbstractTranslator.java:106)
	at wyil.util.AbstractTranslator.visitDeclaration(AbstractTranslator.java:69)
	at wyjs.tasks.JavaScriptCompiler.visitModule(JavaScriptCompiler.java:114)
	at wyjs.tasks.JavaScriptCompileTask.run(JavaScriptCompileTask.java:88)
	at wyjs.Main.run(Main.java:127)
	at wyjs.Main.main(Main.java:216)
```
Need some better error reporting to diagnose this.

**Comment by DavePearce** [comment]
The error appears to be on line `991` of `app.whiley`:

```Whiley
    &State<S> state = new State{app:app,root:root,rendering:null,window:win}
```

**Comment by DavePearce** [comment]
This is the minimal program I have so far which illustrates the problem:

```Whiley
import to_string from std::ascii
import string from js::core

public type State<S> is { int x }

public method run<S>():
    &State<S> state = new State{x:0}

// from web::io

public type Action<S> is { method(&State<S>)->(Action<S>[]) apply }

public function tabindex<S>(int index) -> Attribute<S>:
    return { key: "tabindex", value: (string) to_string(index) }

public type Event is { int timeStamp }
public type handler<E,S> is function(E,S)->(S,Action<S>[])
public type EventAttribute<S> is {
    string event,
    handler<Event,S> handler
}

public type Attribute<S> is EventAttribute<S>

public type Element<S> is {
    string name,
    Attribute<S>[] attributes,
    Node<S>[] children    
}

public type Node<S> is  Element<S> | string
```

**Comment by DavePearce** [comment]
This has something to do with `build.library = true` or not.
